name: Update Calendar Image

on:
  schedule:
    - cron: '25 * * * *'
    - cron: '55 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: python update_calendar.py

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.png
        git commit -m "Update calendar image" || exit 0
        git push origin HEAD:main
